version: "3.1"

services:
  oracle:
    image: oracle:11g
    shm_size: 1g
    environment:
      - ORACLE_PWD=Oracle11g
    ports:
      - 1521:1521
    volumes:
      - ./scripts:/scripts
    container_name: oracle-xe
    restart: always